### PR TITLE
Generalize and adds various comparisons functions + improve default real number comparison method.

### PR DESCRIPTION
**Pull request by tylov**
1. Improved default accuracy handling for real numbers: relative accuracy error. (tol < 0). _TOL still uses absolute error spec.
2. Added ASSERT_NOT_STR(), ASSERT_STRSTR() and ASSERT_NOT_STRSTR() + wide string versions - search for containing string.
3. Added ASSERT_LT(), ASSERT_LE(), ASSERT_GT(), ASSERT_GE() - integer comparisons functions with useful error reporting.
4. Added ASSERT_FLT_NEAR(), ASSERT_FLT_FAR() - uses float relative accuracy error (range independent).
5. Added ASSERT_DBL_LT(), ASSERT_DBL_GT() -  - double comparisons functions with useful error reporting.

Added some tests. This is a compact and minimum code change to add this functionality.

### CODE REVIEW

**Comment by bvdberg** [comment]
Overall looks good, thanks. Some minor points:
- is there a reason to change the SEGFAULT default in main.c?
- get_compare_result() and approximate_equal() can be static
- some trailing spaces (ctest.h line 391)

If you update those, I can merge the patch.

Thanks

**Comment by tylov** [comment]
Great, I will fix those minors and move approximately_equal() to just before assert_dbl_compare() where it is used.

When not on Linux I use MinGW-w64 gcc and clang on Windows (from winlibs.com). They have only partial POSIX support, but is the only missing function is kill(). Is it needed to actually call kill here, or could you force another termination signal?

**Comment by bvdberg** [comment]
I now seem to get some warnings:

In file included from main.c:10:
./ctest.h:530:19: warning: implicit conversion changes signedness: 'clock_t' (aka 'long') to 'uint64_t' (aka 'unsigned long') [-Wsign-conversion]
    uint64_t t1 = clock();
             ~~   ^~~~~~~
./ctest.h:589:19: warning: implicit conversion changes signedness: 'clock_t' (aka 'long') to 'uint64_t' (aka 'unsigned long') [-Wsign-conversion]
    uint64_t t2 = clock();
             ~~   ^~~~~~~
In file included from main.cpp:10:
./ctest.h:530:19: warning: implicit conversion changes signedness: 'clock_t' (aka 'long') to 'uint64_t' (aka 'unsigned long') [-Wsign-conversion]
    uint64_t t1 = clock();
             ~~   ^~~~~~~
./ctest.h:589:19: warning: implicit conversion changes signedness: 'clock_t' (aka 'long') to 'uint64_t' (aka 'unsigned long') [-Wsign-conversion]
    uint64_t t2 = clock();

**Comment by bvdberg** [comment]
I still get some warnings:
clang -Wall -Wextra -Wconversion -Wredundant-decls -Wshadow -Wno-unused-parameter -O3 -c -o main.c.o main.c
In file included from main.c:10:
./ctest.h:592:146: warning: implicit conversion from 'long' to 'double' may lose precision [-Wimplicit-int-float-conversion]
    snprintf(results, sizeof(results), "RESULTS: %d tests (%d ok, %d failed, %d skipped) ran in %.1f ms", total, num_ok, num_fail, num_skip, (t2 - t1)*1000.0/CLOCKS_PER_SEC);
                                                                                                                                              ~~~^~~~ ~
1 warning generated.
clang -Wall -Wextra -Wconversion -Wredundant-decls -Wshadow -Wno-unused-parameter -O3 -c -o mytests.c.o mytests.c
clang  main.c.o mytests.c.o -o test
ln -fs main.c main.cpp
clang++ -Wall -Wextra -Wconversion -Wredundant-decls -Wshadow -Wno-unused-parameter -O3 -c -o main.cpp.o main.cpp
In file included from main.cpp:10:
./ctest.h:592:146: warning: implicit conversion from 'long' to 'double' may lose precision [-Wimplicit-int-float-conversion]
    snprintf(results, sizeof(results), "RESULTS: %d tests (%d ok, %d failed, %d skipped) ran in %.1f ms", total, num_ok, num_fail, num_skip, (t2 - t1)*1000.0/CLOCKS_PER_SEC);
                                                                                                                                              ~~~^~~~ ~
1 warning generated.

**Comment by bvdberg** [comment]
THx! I merged it into master

**Pull request closed without merging**
