### PR TITLE
maintain a definition (USE_COLORS) for the use of colors

### PR DESCRIPTION
**Pull request by chwress**
Hi,

In my project I specify the use of colors during the build process. To this end I've introduced a definition (USE_COLORS) that allows to turn on or off the use of colors at compile time..

Thanks, Chris.

### CODE REVIEW

**Comment by bvdberg** [comment]
I think your goal is valid, but I would like to see USE_COLORS as platform independent,
so not within WIN32 defines.
Also color_output is always set in main(), so the define doesn't really fix anything..
I think it would be good for some users to completely disable color output in the build.

**Comment by chwress** [comment]
You are absolutely right, not sure how I've overlooked this :/

Also wrt the WIN32 define: This should be checked during configuring the build anyways. I placed the check there as an additional security net, since the way colors are set in ctest doesn't work on Windows---I'm not certain if this still is the case for most recent versions (> Windows7).

I've updated the branch and move the check for USE_COLORS to ctest's main function

**Comment by chwress** [comment]
Alternatively there is CTEST_USECOLORS branch containing a single commit as patch.

**Comment by bvdberg** [comment]
i'll look into it tonight...

**Comment by bvdberg** [comment]
I've turned around the default: default is colours on, but users can disable..

**Pull request closed without merging**
